dataSource:
  nation: 'default'
  member: 'default'
  addon: 'default'
  misc: 'default'
  territory: 'default'
  schematic: 'default'
  grade: 'default'
  bank: 'default'
member:
  regexFilter: '^[a-zA-Z0-9가-힣]*.'
  displayMaxLength: 16
  maximumMember: 10
  maximumRankMember:
    OWNER: 0
    OFFICER: 2
    SENIOR: 3
    RESIDENCE: 10
  display:
    OWNER: '왕'
    OFFICER: '부왕'
    SENIOR: '기사단장'
    RESIDENT: '시민'
territory:
  worlds:
    - world
  maximumHeight: 128
  castleItemName: '&6성 설치권'
  outpostItemName: '&6전초기지 설치권'
  maximumCastleCount: 3
  maximumOutpostCount: 3
  nearestDistanceCastleToClaim: 150.0
  nearestDistanceOutpostToClaim: 30.0
  castleLength: 100
  outpostLength: 5
  schematic:
    castle: 'castle.schem'
    outpost: 'outpost.schem'
  schematicOffset:
    castle:
      x: 25
      y: 0
      z: 0
    outpost:
      x: 0
      y: 0
      z: 0
  deleteRange:
    castle:
      weightX: 25
      lengthZ: 25
      height: 128
      depth: 0
    outpost:
      weightX: 2
      lengthZ: 2
      height: 5
      depth: 0
grade:
  '1': '길드'
  '2': '국가'
  '3': '제국'
