package com.minepalm.nations

object ResultCode {

    const val PROGRESS = "PROGRESS"
    const val SUCCESSFUL = "SUCCESSFUL"
    const val EVENT_CANCELLED = "EVENT_CANCELLED"
    const val NO_PERMISSION = "NO_PERMISSION"
    const val NATION_MISMATCH = "NATION_MISMATCH"
    const val REACH_MAXIMUM_MEMBER = "REACH_MAXIMUM_MEMBER"
    const val ALREADY_HAS_NATION = "ALREADY_HAS_NATION"
    const val ASSERT_FAILED = "ASSERT_FAILED"
    const val DISPLAY_NAME_TOO_LONG = "DISPLAY_NAME_TOO_LONG"
    const val DISPLAY_NAME_BAD_WORD = "DISPLAY_NAME_BAD_WORD"
    const val INVALID_DISPLAY_NAME = "INVALID_DISPLAY_NAME"
    const val INVALID_RANK_NAME = "INVALID_RANK_NAME"
    const val ALREADY_NAME_EXIST = "ALREADY_NAME_EXIST"
    const val NO_BEACON = "NO_BEACON"
    const val PREPARE_COMPLETE = "PREPARE_COMPLETE"
    const val OWNER_MISMATCH = "OWNER_MISMATCH"
    const val NO_NATION = "NO_NATION"
    const val NATION_NOT_EXISTS = "NATION_NOT_EXISTS"
    const val NATION_OWNER = "NATION_OWNER"
    const val NATION_PLAYER_NOT_EXISTS = "NATION_PLAYER_NOT_EXISTS"
    const val NO_PERMISSION_THAN_USER = "NO_PERMISSION_THAN_USER"
    const val INVALID_RANK = "INVALID_RANK"
    const val PLAYER_NOT_EXISTS = "PLAYER_NOT_EXISTS"
    const val PLAYER_NOT_ONLINE = "PLAYER_NOT_ONLINE"
    const val UNCHECKED_EXCEPTION = "UNCHECKED_EXCEPTION"

    const val REACH_MAX_CASTLE = "REACH_MAX_CASTLE"
    const val REACH_MAX_OUTPOST = "REACH_MAX_OUTPOST"
    const val TOO_CLOSE = "TOO_CLOSE"
    const val TOO_HIGH = "TOO_HIGH"
    const val INVALID_WORLD = "INVALID_WORLD"

    const val REACHED_MAX_LEVEL = "REACHED_MAX_LEVEL"
    const val REQUIREMENTS_FAILED = "REQUIREMENTS_FAILED"
    const val REQUIREMENTS_NOT_EXIST = "REQUIREMENTS_NOT_EXIST"

    const val INVALID_AMOUNT = "INVALID_AMOUNT"
    const val EXCEEDED_AMOUNT = "EXCEEDED_AMOUNT"

    const val HOME_ALREADY_IN_WAR = "HOME_ALREADY_IN_WAR"
    const val AWAY_ALREADY_IN_WAR = "HOME_ALREADY_IN_WAR"
    const val HOME_FORCED_SHIELD = "HOME_FORCED_SHIELD"
    const val AWAY_HAS_SHIELD = "AWAY_HAS_SHIELD"
    const val ALREADY_DESTROYED = "ALREADY_DESTROYED"
    const val NO_WAR = "NO_WAR"


}